### ISSUE TITLE
Bookings - Alterations

### ISSUE THREAD

**Issue by atoff** [VATSIM-UK/ukts-core-api#25]
1. Bookings should be able to have a "network_type"
* One of: Network or Sweatbox

2. Bookings should be able to have multiple positions associated with them

3. Booking logic must be altered to adapt to the above
* When creating a network booking (any user), it should check for other network bookings (and vice versa with sweatbox)

**Comment by AxonC** [comment]
@atoff one for you

**Comment by keanucz** [comment]
Do ya reckon I could have a go at this?

**Comment by atoff** [comment]
Go for it. Have assigned you. Let us know if you need any help.

**Comment by keanucz** [comment]
Looking at this again, not sure what "Bookings should be able to have multiple positions associated with them" really means. Does this mean that you should be able to book multiple positions at once??

**Comment by atoff** [comment]
This is mainly targeted at bookings for events, where multiple positions can be booked in one booking. Essentially, on the Booking model, the positions relationship should be a hasMany with the associated pivot table

**Comment by keanucz** [comment]
Ah, I see. Thanks!

**Comment by Keanu73** [comment]
Just to clarify, what do you mean by a "pivot table"?

**Comment by atoff** [comment]
Hi @Keanu73, did you get anywhere with this?

**Comment by keanucz** [comment]
I was, actually, though I stopped working on it after I decided to work on something else - I can have a go at it again if you want

**Comment by atoff** [comment]
If your still happy to, it would be great if you could see if through to completion? Otherwise share what you have done so far and we can take a look at getting this done :)

**Comment by keanucz** [comment]
Defo will do
