### ISSUE TITLE
[BE] User - I can have availability

### ISSUE THREAD

**Issue by atoff** [VATSIM-UK/ukts-core-api#26]
### Description:
A user should be able to define (multiple) time periods for a specific day (or range of dates) when they are available for mentoring or exams (i.e for a session)

### Acceptance Criteria / Requirements:
AC1: The user should be able create availability for a single date or a range of dates (i.e. can book 17:00 to 20:00 on the 27/11/2019 or 27/11/2019 - 30/11/2019
AC2: The user should be able to block update the availability across a range days or just for a single day
AC3: The user should be able to remove availability across a range days or just for a single day, or delete all of their availability outright
AC4: There should be a system of removing old availability from the database on a regular basis (daily)
AC5: Users cannot book availability in the past.
AC6: Users cannot book availability within an date/time range that they already have booked
AC7: The minimum availability that can be booked for is X minutes (as defined in a configuration variable). This should be enforced on the GraphQL mutation, and *not* the model level.

**Comment by aaronholtomcook** [comment]
@atoff  @AxonC 

I was thinking for this:

id(INT/UUID) user_id(INT fKey to users?) start(DATETIME) end(DATETIME)

If you're happy with that table structure I'll get started on it. Just two questions:

1. Where is the user table I associate the key to?
2. I'm happy to make a cron job for AC4, would it be using Kernel in laravel, every 24 hours DELETE where end < NOW().

**Comment by atoff** [comment]
Sounds about right to me. We tend not to use fKey's, favouring laravel relationships and/or boot methods to give us more control. In addition to this, as the user model is remote via UK Auth, fKeys for user_id's won't work. I'll assign this issue to you, when you work on it can you do so in a branch on your fork, such as core/feature/26-user-availability?

In answer to your questions:
1) Our Next-Gen API Microservices depend on the Auth API (vatsim-uk/auth) for user information. The Laravel Model "User" extends part of our custom auth package (vatsim-uk/auth-package) called Remote Models, which allows us to query user information from the Auth API in an Eloquent way.
2. Yep, use the Laravel Scheduler to run a purge command on out dated availability daily: `Availability::where('end_at', '<', Carbon::now())` or such

**Comment by aaronholtomcook** [comment]
Thanks for the quick answer - i'll get started on it 👍

**Comment by aaronholtomcook** [comment]
@atoff do we want to add some more A/C?

AC5: Users cannot book availability in the past.
AC6: Users cannot book availability within a date/time range that they already have booked
AC7: The minimum availability that can be booked is 30 minutes.

**Comment by atoff** [comment]
Have added AC5-6, however not sure if/by how much we want to limit the amount of availability that can be booked. @AxonC thoughts?

**Comment by AxonC** [comment]
> Have added AC5-6, however not sure if/by how much we want to limit the amount of availability that can be booked. @AxonC thoughts?

Think they are both sensible to me - the amount of availability should probably be a decision at Div Policy level, not something from us. Just a configurable value would be fine I think.
