### ISSUE TITLE
[Refactor] Migrate dates to ISO8601 format

### ISSUE THREAD

**Issue by AxonC** [VATSIM-UK/ukts-core-api#37]
### Description:
Migrate the GraphQL dateformat to ISO8601 format.

### Accceptance Criteria / Requirements:
AC1: Dates are stored and accepted in an ISO8601 format.

**Comment by aaronholtomcook** [comment]
Think this is a non-issue. Dates in the db are stored as a TIMEZONE which will always be UTC/Zulu format.

As the system will be using zulu time then don't think we need to do this.

**Comment by aaronholtomcook** [comment]
https://github.com/VATSIM-UK/ukts-core-api/pull/41

**Comment by AxonC** [comment]
Thanks @aaronholtomcook for the work :)

**Comment by keanucz** [comment]
Heh, you beat me to it! :P
